### PR TITLE
Add icons and favicon

### LINKED ISSUE #8: Add icons and favicon
Guide: https://www.favicon-generator.org/
Logo: https://drive.google.com/drive/folders/1u7Wz4lPOiG7u4aRxp5MAgi46F8vob0UM?usp=sharing

### PR DESCRIPTION
**Pull request by KoushikSahu**
Issue resolved: #8 
Added icons and favicons of all platforms and sizes. 

There are 4 directories added named android, apple, ms, favicon. If further along the project we need to work on any specific platform then the images required can be put in the directory of the respective platform without requiring us to create additional directories.

The public directory tree looks like this now:-

public
├── favicon.ico
├── img
│   ├── android
│   │   ├── android-icon-144x144.png
│   │   ├── android-icon-192x192.png
│   │   ├── android-icon-36x36.png
│   │   ├── android-icon-48x48.png
│   │   ├── android-icon-72x72.png
│   │   └── android-icon-96x96.png
│   ├── apple
│   │   ├── apple-icon-114x114.png
│   │   ├── apple-icon-120x120.png
│   │   ├── apple-icon-144x144.png
│   │   ├── apple-icon-152x152.png
│   │   ├── apple-icon-180x180.png
│   │   ├── apple-icon-57x57.png
│   │   ├── apple-icon-60x60.png
│   │   ├── apple-icon-72x72.png
│   │   ├── apple-icon-76x76.png
│   │   ├── apple-icon.png
│   │   └── apple-icon-precomposed.png
│   ├── favicon
│   │   ├── favicon-16x16.png
│   │   ├── favicon-32x32.png
│   │   ├── favicon-96x96.png
│   │   └── favicon.ico
│   ├── ms
│   │   ├── ms-icon-144x144.png
│   │   ├── ms-icon-150x150.png
│   │   ├── ms-icon-310x310.png
│   │   └── ms-icon-70x70.png
│   └── opencode.png
├── index.html
├── manifest.json
└── robots.txt

### CODE REVIEW

**Review by DesignrKnight — APPROVED** [review]

**Review by nayakashutosh9 — APPROVED** [review]

**Comment by DesignrKnight** [comment]
@all-contributors add @all-contributors as tool

**Comment by DesignrKnight** [comment]
@all-contributors add @nayakashutosh9 for Maintenance, Project Management, Reviewed Pull Requests,

**Comment by DesignrKnight** [comment]
@all-contributors add @007vedant for Project Management, Code

**Comment by DesignrKnight** [comment]
@all-contributors add @ankitkumarsamota121 for Project Management, Code

**Comment by DesignrKnight** [comment]
@all-contributors add @riteshsp2000  for Project Management, Code

**Comment by DesignrKnight** [comment]
@all-contributors add @DesignrKnight for Project Management, Code

**Pull request merged**
