### PR TITLE
Format setup

### PR DESCRIPTION
**Pull request by riteshsp2000**
1. Add Prettier config
2. Add eslint config
3. Add vscode editor config

### CODE REVIEW

**Review by aksamota — APPROVED** [review]
Seems Good to me 👍

**Review by aksamota — CHANGES_REQUESTED** [review]
Remove the file Navbar.css.js

**Comment by DesignrKnight** [comment]
Can you add Prettier to CI at GitHub Actions so that upstream always has standardized code even if someone does not pretty before PR

**Comment by riteshsp2000** [comment]
@ankitkumarsamota121  Yup ill remove it.
@DesignrKnight  Okay cool, ill add it to GitHub actions as well.

**Comment by DesignrKnight** [comment]
Seems good. Will know the Actions status only when a new PR is made after this is merged

**Comment by riteshsp2000** [comment]
@DesignrKnight @ankitkumarsamota121 I created a separate prettier yaml file. Is there any other step I should take so that the checks start? Because I don't seem to find the prettier workflow being used in this current PR

**Comment by DesignrKnight** [comment]
From what I understand, it'll run only after it is in main. Now it is just in the PR

**Review by aksamota — APPROVED** [review]
Seems Good to me 👍

**Comment by DesignrKnight** [comment]
@riteshsp2000 @ankitkumarsamota121 
Do check by opening a PR is pretty work in CI

**Pull request merged**
